CHECKPOINT_PATH="Callbacks"
LOG_PATH="lb_logs"
NUM_CLASSES=10
LEARNING_RATE=0.006
LOAD_CHECKPOINTS=False
SAVE_CHECKPOINTS=True

TRAIN=True
PREDICT=True
TEST=True

DATA_PATH="Fmnist"
BATCH_SIZE=100
MAX_EPOCH=30